---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
spec:
  itemPath: "vaults/4kbytax7eoweefgrkbg2af6oxu/items/qh7lyixmeehqmsseeef3v45p2u"
