---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kobo-sync
  namespace: kavita
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            fsGroup: 65532
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: kobo-sync
              image: ghcr.io/subdavis/kobodl@sha256:5439b54edcd16211dd6b1567f1b3a976f21770851be29cf0269de8d52b93717b # sha-79d4d8d
              command: ["sh", "-c"]
              args:
                - |
                  cp /secret/kobodl.json /tmp/kobodl.json &&
                  kobodl --config /tmp/kobodl.json book get --get-all --output-dir /library/kobo --format-str '{Author}/{Title}'
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: config-secret
                  mountPath: /secret
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
                - name: library
                  mountPath: /library
          volumes:
            - name: config-secret
              secret:
                secretName: kobo-credentials
            - name: tmp
              emptyDir: {}
            - name: library
              persistentVolumeClaim:
                claimName: kavita-library-pvc
