---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: gutenberg
  namespace: books
spec:
  schedule: "30 */6 * * *"
  timezone: UTC
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  workflowSpec:
    workflowTemplateRef:
      name: process-gutenberg
