---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount-argo-workflow.yaml
  - role-argo-workflow.yaml
  - rolebinding-argo-workflow.yaml
  - configmap-workflow-semaphore.yaml
  - onepassworditem-anthropic-agent.yaml
  - onepassworditem-kavita-agent.yaml
  - onepassworditem-ovh-archive.yaml
  - workflowtemplate-process-gutenberg.yaml
  - workflowtemplate-process-kobo.yaml
  - workflowtemplate-process-humble.yaml
  - cronworkflow-cleanup-scratch-pvcs.yaml
  - prometheusrule-argo-workflows.yaml
