---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: convert-comics-humble
  namespace: books
spec:
  schedule: "0 0 1 1 *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: kcc
              image: ghcr.io/ciromattia/kcc:v9.4.3
              command: ["sh", "-c"]
              env:
                - name: BUNDLE_NAME
                  value: "CHANGE_ME"
              args:
                - |
                  find "/books/sources/humble-bundle/$BUNDLE_NAME" -name '*.pdf' | head -1 | grep -q . || { echo "No .pdf files to process"; exit 0; }
                  mkdir -p /books/incoming/comics /books/markers/humble-comics &&
                  find "/books/sources/humble-bundle/$BUNDLE_NAME" -name '*.pdf' | while read -r pdf; do
                    marker="/books/markers/humble-comics/$(basename "$pdf").done"
                    [ -f "$marker" ] && continue
                    # Skip non-HQ version when an HQ variant exists in the same directory
                    if ls "$(dirname "$pdf")"/*HQ*.pdf >/dev/null 2>&1 && \
                       ! echo "$(basename "$pdf")" | grep -qi 'HQ'; then
                      echo "Skipping non-HQ: $pdf (HQ version available)"
                      touch "$marker"
                      continue
                    fi
                    # Get parent directory name and normalize for comictagger
                    # Format: "Series Name X.cbz" (matches epub2cbz output format)
                    parent_name=$(basename "$(dirname "$pdf")")
                    # Normalize naming: handle double-space separator
                    # If "Vol. N" before double-space, strip subtitle; otherwise keep sub-series name
                    if echo "$parent_name" | grep -qE ' (Vol|Volume) ?\.? ?[0-9]+  '; then
                      # Volume with subtitle: "The Boys Vol. 1  The Name of the Game" → "The Boys 1"
                      output_name=$(printf '%s' "$parent_name" | sed -E '
                        s/  +.*$//
                        s/ (Volume|Vol) ?\.? ?([0-9]+)$/ \2/
                      ')
                    else
                      # Sub-series or simple: normalize double-space, extract #N or Vol N
                      output_name=$(printf '%s' "$parent_name" | sed -E '
                        s/  +/ /g
                        s/ #0*([0-9]+).*$/ \1/
                        s/ (Volume|Vol) ?\.? ?([0-9]+)$/ \2/
                      ')
                    fi
                    # Append " 1" for one-shots without a volume number
                    if ! echo "$output_name" | grep -qE ' [0-9]+$'; then
                      output_name="${output_name} 1"
                    fi
                    echo "Converting: $pdf -> ${output_name}.cbz"
                    pdf_basename=$(basename "$pdf" .pdf)
                    c2e -n -f CBZ -o /books/incoming/comics "$pdf" &&
                    mv "/books/incoming/comics/${pdf_basename}.cbz" "/books/incoming/comics/${output_name}.cbz" &&
                    touch "$marker"
                  done
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 4Gi
                limits:
                  memory: 4Gi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: library
                  mountPath: /books
          volumes:
            - name: tmp
              emptyDir: {}
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
