---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-kobo
  namespace: books
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: kobodl
              image: ghcr.io/subdavis/kobodl@sha256:5439b54edcd16211dd6b1567f1b3a976f21770851be29cf0269de8d52b93717b # sha-79d4d8d
              command: ["sh", "-c"]
              args:
                - |
                  cp /secret/kobodl.json /tmp/kobodl.json &&
                  mkdir -p /books/sources/kobo &&
                  kobodl --config /tmp/kobodl.json book get --get-all --output-dir /books/sources/kobo --format-str '{Title} - {Author} ({ShortRevisionId})'
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: config-secret
                  mountPath: /secret
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
                - name: library
                  mountPath: /books
          volumes:
            - name: config-secret
              secret:
                secretName: kobo-credentials
            - name: tmp
              emptyDir: {}
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
