---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: comictagger-manga
  namespace: books
spec:
  schedule: "30 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: comictagger
              image: ghcr.io/bendwyer/containers/comictagger@sha256:dfb3a48a21ce90c2f1708c7192e0d5e07502b56cd0b4333817394aab4c725b32 # 1.6.0b9
              command: ["sh", "-c"]
              args:
                - |
                  comictagger \
                    --no-gui \
                    -s \
                    -o \
                    -f \
                    --tags-write cr \
                    --source mangabaka \
                    --no-abort \
                    --config /config \
                    /books/incoming/manga &&
                  comictagger \
                    --no-gui \
                    -r \
                    --tags-read cr \
                    --no-abort \
                    --move \
                    --dir /books/library/manga \
                    --template "{series}/{series} #{issue} ({year})" \
                    --config /config \
                    /books/incoming/manga
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: tmp
                  mountPath: /tmp
                - name: library
                  mountPath: /books
          volumes:
            - name: config
              emptyDir: {}
            - name: tmp
              emptyDir: {}
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
