---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: humble-sync-comics
  namespace: books
spec:
  schedule: "0 0 1 1 *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          initContainers:
            - name: humble-download
              image: ghcr.io/bendwyer/containers/humble-cli@sha256:0a5b50588235710f77f7055bd40d1184edd3e7395a3dc5cfabcc8b28287c19a9 # 0.21.3
              command: ["sh", "-c"]
              args:
                - |
                  export HOME=/tmp &&
                  humble-cli auth "$(cat /secret/session-key)" &&
                  mkdir -p /staging/comics &&
                  cd /staging/comics &&
                  echo "$BUNDLE_KEY" > /tmp/bundles.txt &&
                  humble-cli bulk-download /tmp/bundles.txt --format pdf --cur-dir
              env:
                - name: BUNDLE_KEY
                  value: "CHANGE_ME"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: config-secret
                  mountPath: /secret
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
                - name: staging
                  mountPath: /staging
          containers:
            - name: kcc-convert
              image: ghcr.io/ciromattia/kcc:v9.4.3
              command: ["sh", "-c"]
              args:
                - |
                  mkdir -p /books/incoming/comics &&
                  for pdf in /staging/comics/*.pdf; do
                    [ -f "$pdf" ] || continue
                    kcc-c2e -p KoA -f CBZ -o /books/incoming/comics "$pdf"
                  done
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 1Gi
              volumeMounts:
                - name: staging
                  mountPath: /staging
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
                - name: library
                  mountPath: /books
          volumes:
            - name: config-secret
              secret:
                secretName: humble-credentials
            - name: tmp
              emptyDir: {}
            - name: staging
              emptyDir: {}
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
