---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metadata-ebook-kobo
  namespace: books
spec:
  schedule: "20 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: ebook-metadata
              image: ghcr.io/bendwyer/containers/ebook-metadata:1
              imagePullPolicy: Always
              args:
                - --input-dir
                - /books/sources/kobo
                - --output-dir
                - /books/library/ebooks
                - --marker-dir
                - /books/markers/kobo
                - --provider
                - kobo
                - --country
                - de
                - --language
                - en
                - --skip-large
                - "50"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: library
                  mountPath: /books
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
            - name: tmp
              emptyDir: {}
