---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ebook-stage
  namespace: books
spec:
  schedule: "10 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: ebook-stage
              image: alpine:3.21
              command: ["sh", "-c"]
              args:
                - |
                  mkdir -p /books/markers/ebooks
                  for f in /books/sources/kobo/*.epub; do
                    [ ! -f "$f" ] && continue
                    size=$(stat -c%s "$f" 2>/dev/null || stat -f%z "$f")
                    # Skip files >= 50MB (manga handled by epub2cbz)
                    [ "$size" -ge 52428800 ] && continue
                    name=$(basename "$f")
                    marker="/books/markers/ebooks/${name}.staged"
                    [ -f "$marker" ] && continue
                    cp "$f" "/books/incoming/ebooks/"
                    touch "$marker"
                  done
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 128Mi
              volumeMounts:
                - name: library
                  mountPath: /books
          volumes:
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
