---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: convert-manga-humble
  namespace: books
spec:
  schedule: "0 0 1 1 *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: kcc
              image: ghcr.io/ciromattia/kcc:v9.4.3
              command: ["sh", "-c"]
              env:
                - name: BUNDLE_NAME
                  value: "CHANGE_ME"
              args:
                - |
                  find "/books/sources/humble-bundle/$BUNDLE_NAME" -name '*.pdf' | head -1 | grep -q . || { echo "No .pdf files to process"; exit 0; }
                  mkdir -p /books/incoming/manga /books/markers/humble-manga &&
                  find "/books/sources/humble-bundle/$BUNDLE_NAME" -name '*.pdf' | while read -r pdf; do
                    marker="/books/markers/humble-manga/$(basename "$pdf").done"
                    [ -f "$marker" ] && continue
                    # Get parent directory name and normalize for comictagger
                    # Format: "Series Name X.cbz" (matches epub2cbz output format)
                    parent_name=$(basename "$(dirname "$pdf")")
                    # Strip subtitle after double-space, convert Vol/Volume to just number
                    output_name=$(printf '%s' "$parent_name" | sed -E '
                      s/  +.*$//
                      s/ (Volume|Vol) ?\.? ?([0-9]+)$/ \2/
                    ')
                    # Append " 1" for one-shots without a volume number
                    if ! echo "$output_name" | grep -qE ' [0-9]+$'; then
                      output_name="${output_name} 1"
                    fi
                    echo "Converting: $pdf -> ${output_name}.cbz"
                    pdf_basename=$(basename "$pdf" .pdf)
                    c2e -n -f CBZ -o /books/incoming/manga "$pdf" &&
                    mv "/books/incoming/manga/${pdf_basename}.cbz" "/books/incoming/manga/${output_name}.cbz" &&
                    touch "$marker"
                  done
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  cpu: 100m
                  memory: 4Gi
                limits:
                  memory: 4Gi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                - name: library
                  mountPath: /books
          volumes:
            - name: tmp
              emptyDir: {}
            - name: library
              persistentVolumeClaim:
                claimName: library-shared-pvc
