---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
  namespace: books
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: bjw-s
  values:
    controllers:
      calibre:
        pod:
          terminationGracePeriodSeconds: 300
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/calibre
              digest: sha256:296486899c825c5106b0de5672c0b14188ae7e45003b2c33b767c6bc32090ee2 # 8.16.2
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Berlin
              PUID: "1000"
              PGID: "1000"
            resources:
              requests:
                cpu: 250m
                memory: 4Gi
              limits:
                memory: 4Gi
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /
                port: 8080
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
              readiness:
                enabled: true
                type: HTTP
                path: /
                port: 8080
                spec:
                  initialDelaySeconds: 10
                  periodSeconds: 10
    service:
      calibre:
        controller: calibre
        ports:
          http:
            port: 8080
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-pvc
        globalMounts:
          - path: /config
      library:
        enabled: true
        existingClaim: library-pvc
        globalMounts:
          - path: /books
