---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: books
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: bjw-s
  values:
    controllers:
      filebrowser:
        containers:
          app:
            image:
              repository: filebrowser/filebrowser
              tag: v2.56.0
              pullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 128Mi
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /health
                port: 80
                spec:
                  initialDelaySeconds: 10
                  periodSeconds: 10
              readiness:
                enabled: true
                type: HTTP
                path: /health
                port: 80
                spec:
                  initialDelaySeconds: 5
                  periodSeconds: 5
    service:
      filebrowser:
        controller: filebrowser
        ports:
          http:
            port: 80
    persistence:
      incoming:
        enabled: true
        existingClaim: library-shared-pvc
        globalMounts:
          - path: /srv
            subPath: incoming
