---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cwa
  namespace: books
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: bjw-s
  values:
    controllers:
      cwa:
        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: v4.0.3
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Berlin
              PUID: "1000"
              PGID: "1000"
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /
                port: 8083
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                type: HTTP
                path: /
                port: 8083
                spec:
                  initialDelaySeconds: 5
                  periodSeconds: 5
    service:
      cwa:
        controller: cwa
        ports:
          http:
            port: 8083
    persistence:
      config:
        enabled: true
        existingClaim: cwa-config-pvc
        globalMounts:
          - path: /config
          - path: /calibre-library
      books:
        enabled: true
        existingClaim: library-shared-pvc
        globalMounts:
          - path: /books
