---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lazylibrarian
  namespace: books
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: bjw-s
  values:
    controllers:
      lazylibrarian:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/lazylibrarian
              digest: sha256:90c75a831faf84bfa780e1d3950078ff03b6280dad0bde860c6864a68dca93d7 # 2daa3258-ls246
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Berlin
              PUID: "1000"
              PGID: "1000"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /home
                port: 5299
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
              readiness:
                enabled: true
                type: HTTP
                path: /home
                port: 5299
                spec:
                  initialDelaySeconds: 10
                  periodSeconds: 10
    service:
      lazylibrarian:
        controller: lazylibrarian
        ports:
          http:
            port: 5299
    persistence:
      config:
        enabled: true
        existingClaim: lazylibrarian-config-pvc
        globalMounts:
          - path: /config
      library:
        enabled: true
        existingClaim: library-shared-pvc
        globalMounts:
          - path: /books
