---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omni-tls-cert
  namespace: omni
spec:
  secretName: omni-tls
  issuerRef:
    name: letsencrypt-prod-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - ${OMNI_SUBDOMAIN}.${OMNI_DOMAIN}
    - "*.proxy.${OMNI_DOMAIN}"
