---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: omni
  namespace: omni
spec:
  itemPath: vaults/7couors34y2zkkjlbsyektvaxi/items/kwe5f6hctwfaf47qnayaruvyqi
