---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: etcd
  namespace: omni
spec:
  itemPath: "vaults/7couors34y2zkkjlbsyektvaxi/items/uo5xpahoeoufu7pk7m2rzabvda"
