---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: bjw-s
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  # uninstall:
  #   keepHistory: false
  values:
    controllers:
      calibre:
        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V3.1.4
              pullPolicy: IfNotPresent
            env:
              PUID: 1000
              PGID: 1000
              TZ: Europe/Berlin
            resources:
              requests:
                cpu: 250m
                memory: 1Gi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /
                port: 8083
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                type: HTTP
                path: /
                port: 8083
                spec:
                  initialDelaySeconds: 5
                  periodSeconds: 5
    service:
      calibre:
        controller: calibre
        ports:
          http:
            port: 8083
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-pvc
        globalMounts:
          - path: /config
      library:
        enabled: true
        existingClaim: calibre-library-pvc
        globalMounts:
          - path: /calibre-library
      ingest:
        enabled: true
        existingClaim: calibre-ingest-pvc
        globalMounts:
          - path: /cwa-book-ingest
