---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
  namespace: calibre-web-automated
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: calibre-web-automated
