---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-library-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-ingest-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
